on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
    name: Create Release
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: version
        run: echo "::set-output name=version::$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)"
        id: version
      - name: artifact
        run: echo "::set-output name=artifact::$(mvn help:evaluate -Dexpression=project.artifactId -q -DforceStdout)"
        id: artifact
      - run: mvn --batch-mode --update-snapshots clean package -DfinalName=${{ steps.artifact.outputs.artifact }}-${{ steps.version.outputs.version }}
      - name: release

        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: target/${{ steps.artifact.outputs.artifact }}-${{ steps.version.outputs.version }}.zip
          asset_name: ${{ steps.artifact.outputs.artifact }}-${{ steps.version.outputs.version }}.zip
          asset_content_type: application/zip